### ISSUE TITLE
docker image -> run cmd parameter is --config not --configFile

### ISSUE THREAD

**Issue by Naboo2604** [chr-fritz/knx-exporter#22]
**Describe the bug**
in the docker image the preconfigured run CMD is:
`run --config /etc/.knx-exporter.yaml`

...but the binary use --configFile als (long)parameter

This produce the following error in the container:

> Error: can not read group address configuration: open config.yaml: no such file or directory
> can not read group address configuration: open config.yaml: no such file or directory
> Usage:
>   knx-exporter run [flags]
> Flags:
>   -f, --configFile string   The knx configuration file. (default "config.yaml")
>   -h, --help                help for run
>   -p, --port uint16         The port where all metrics should be exported. (default 8080)
>   -r, --restart string      The restart behaviour. Can be health or exit (default "health")
> Global Flags:
>       --config string      config file (default is $HOME/.knx-exporter.yaml)
>   -v, --log_level string   The minimum log level to print the messages (default "info")

**To Reproduce**
1. docker pull quay.io/chrfritz/knx-exporter
2. start container
3. see the error above in container log...

**Expected behavior**
please change the CMD in docker config to:
`run --configFile /etc/.knx-exporter.yaml`

**Comment by chr-fritz** [comment]
I checked the behaviour. Technically the Dockerfile is correct but there was a bug reading the values from the first config file which contains the path to the group address configuration file, so the search path to that file wasn't correct.

This bug is no fixed in the latest release v0.2.5 and I added a additional section about how to run it using docker.
